extends SceneTree
const Session = preload("res://scripts/table_session.gd")
var checks := 0
var failures := 0
var events: Array = []
var session

func _initialize() -> void: _run.call_deferred()
func check(ok: bool, description: String) -> void:
	checks += 1
	if not ok:
		failures += 1
		push_error("BOARD_GESTURE: " + description)
func tick() -> void:
	session._board_next_tick = 0
	session._process(0.0)
func request(seat: int, sequence: int, index: int, kind: String, offset: Vector2 = Vector2.ZERO, hand: int = -99, room: String = "", board_count: int = -99) -> void:
	session._accept_board_gesture(seat, -seat - 1, session.state.hand_id if hand == -99 else hand, sequence, session.state.room_id if room.is_empty() else room, session.state.board.size() if board_count == -99 else board_count, index, kind, offset)

func _run() -> void:
	session = Session.new()
	root.add_child(session)
	session.set_process(false)
	session.board_gesture.connect(func(seat, sequence, index, kind, offset): events.append([seat, sequence, index, kind, offset]))
	session.request_board_gesture(0, "press", Vector2.ZERO)
	tick()
	check(events.is_empty(), "unseated request rejected")
	session.start_local(["Alice", "Bob"])
	session.request_board_gesture(0, "press", Vector2.ZERO)
	tick()
	check(events.is_empty(), "lobby has no public table cards")
	session.begin_hand()
	var original: Dictionary = session.state.duplicate(true)
	var engine_original: Dictionary = session._engine.snapshot(0).duplicate(true)
	for index in 5: request(0, index + 1, index, "press", Vector2(0.1, -0.2))
	check(events.is_empty(), "authority waits for fixed tick")
	tick()
	check(events.size() == 5 and session.state.board.is_empty(), "all five face-down slots respond before flop")
	for index in 5:
		check(events[index][0] == 0 and events[index][2] == index and events[index][3] == "press", "each card gets its own authoritative owner")
	request(1, 1, 0, "press")
	request(1, 2, 0, "drag", Vector2.ONE)
	request(1, 3, 0, "release")
	tick()
	check(events.size() == 5 and session._board_owners[0] == 0, "first press wins; another player cannot drag or release it")
	for sequence in range(6, 206): request(0, sequence, 0, "drag", Vector2(float(sequence) / 205.0, -0.5))
	check(session._board_pending_drags.size() == 1, "host coalesces a flood to one latest sample")
	tick()
	check(events.size() == 6 and events[-1][4] == Vector2(1, -0.5), "tick sends only latest position")
	request(0, 206, 0, "release")
	request(1, 3, 0, "press")
	tick()
	check(events[-1][3] == "release" and not session._board_owners.has(0), "release bypasses drag limiter; consumed losing request cannot replay")
	check(session.state == original and session._engine.snapshot(0) == engine_original, "gestures never mutate revision, stack, board, deck-visible outcome or turn")
	var count := events.size()
	for bad_index in [-1, 5, 2147483647]: request(0, 207, bad_index, "press")
	for bad_kind in ["", "flip", "PRESS"]: request(0, 207, 0, bad_kind)
	for bad_offset in [Vector2(INF, 0), Vector2(NAN, 0), Vector2(0, -1.01)]: request(0, 207, 0, "press", bad_offset)
	request(0, 207, 0, "press", Vector2.ZERO, 0)
	request(0, 207, 0, "press", Vector2.ZERO, -99, "stale-room")
	request(0, 207, 0, "press", Vector2.ZERO, -99, "", 3)
	request(0, 2147483648, 0, "press")
	request(9, 1, 0, "press")
	session._accept_board_gesture(0, -2, session.state.hand_id, 207, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	session.is_local = false
	session._peer_seats = {1: 0, 7: 1}
	session._accept_board_gesture(0, 7, session.state.hand_id, 207, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	session._accept_board_gesture(1, 99, session.state.hand_id, 207, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	session._request_board_gesture(session.state.hand_id, 207, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	session.is_local = true
	session._peer_seats.clear()
	tick()
	check(events.size() == count, "malformed, stale, replayed, unknown and forged identities are rejected")
	session._board_last_press[0] = -100
	request(1, 4, 0, "press", Vector2(-1, 1))
	tick()
	check(events.size() == count + 1 and events[-1][0] == 1, "legal next owner succeeds after rejected input")
	var last: Array = events[-1]
	session._receive_board_gesture(1, last[1], session.state.hand_id, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	session._receive_board_gesture(0, 999, 0, session.state.room_id, 0, 0, "press", Vector2.ZERO)
	check(events.size() == count + 1, "duplicate and stale echoes rejected")
	session._board_activity[0] = Time.get_ticks_msec() - Session.BOARD_GESTURE_TTL_MS
	tick()
	check(events[-1][0] == 1 and events[-1][3] == "release" and not session._board_owners.has(0), "TTL releases abandoned control")
	for index in [1, 2, 3, 4]: request(0, 210 + index, index, "release")
	tick()
	check(session._board_visible_owners.is_empty(), "release clears every visible owner")
	session._board_last_press.clear()
	session.set_local_seat(0)
	session.request_board_gesture(4, "press", Vector2.ZERO)
	# Raw fixture sequences above intentionally bypassed the local counter.
	session._board_request_sequence = 215
	session.request_board_gesture(4, "press", Vector2.ZERO)
	tick()
	for index in 100: session.request_board_gesture(4, "drag", Vector2(0.5, 0.5))
	check(session._board_client_drags.size() == 1, "local sender also coalesces continuous input")
	session.request_board_gesture(4, "release", Vector2.ONE)
	tick()
	check(session._board_client_drags.is_empty() and events[-1][3] == "release" and events[-1][4] == Vector2.ZERO, "release cancels unsent drag and normalizes resting position")
	session._board_last_press.clear()
	session.request_board_gesture(3, "press", Vector2.ZERO)
	tick()
	var old_sequence: int = session._board_received_sequence
	while session.state.board.is_empty():
		session.set_local_seat(session.state.actor)
		session.submit_action("check" if session.state.legal.get("check", false) else "call")
	check(session._board_owners.is_empty() and session._board_visible_owners.is_empty(), "real flop transition releases control")
	check(session._board_received_sequence == old_sequence, "same-hand board transition keeps replay sequence monotonic")
	count = events.size()
	request(0, 500, 3, "press", Vector2.ZERO, -99, "", 0)
	tick()
	check(events.size() == count, "late preflop press cannot acquire newly revealed flop")
	request(0, 500, 3, "press")
	tick()
	check(events[-1][3] == "press", "valid new-street press works after stale rejection")
	session._on_server_disconnected()
	check(events[-1][3] == "release" and session._board_owners.is_empty(), "disconnect clears held cards immediately")
	count = events.size()
	request(0, 501, 3, "press")
	session._receive_board_gesture(0, 999, session.state.hand_id, session.state.room_id, 3, 3, "press", Vector2.ZERO)
	tick()
	check(events.size() == count, "pause and disconnect latch block later packets")
	session.start_local(["Alice", "Bob"])
	session.begin_hand()
	session.set_local_seat(session.state.actor)
	session.submit_action("all_in")
	check(session.state.players[session.local_seat].stack == 0 and session.state.actor != session.local_seat, "fixture is all-in and not the actor")
	session.request_board_gesture(4, "press", Vector2.ZERO)
	tick()
	check(events.size() == count + 1, "zero-chip non-actor may touch a public card")
	session.request_board_gesture(4, "release", Vector2.ZERO)
	tick()
	# Simulate a malicious long network batch: fake only cooldown time in this fixture.
	for sequence in range(3, 403, 2):
		session._board_last_press.clear()
		request(session.local_seat, sequence, 0, "press")
		request(session.local_seat, sequence + 1, 0, "release")
	check(session._board_edges.size() <= 29 and session._board_owners.is_empty(), "hard queue bound reserves space for all valid releases")
	tick()
	check(session._board_visible_owners.is_empty(), "bounded flood cannot leave visible control stuck")
	count = events.size()
	session.start_solo("Human")
	session.begin_hand()
	request(1, 1, 0, "press")
	tick()
	check(events.size() == count, "bots cannot perform human touch gestures")
	session.request_board_gesture(0, "press", Vector2.ZERO)
	tick()
	check(events.size() == count + 1, "fresh room resets sequences and permits human")
	session.leave_game()
	check(events[-1][3] == "release" and session._board_edges.is_empty() and session._board_client_drags.is_empty(), "leave releases visual state and cancels queued work")
	session.queue_free()
	await process_frame
	print("BOARD_GESTURE checks=%d failures=%d" % [checks, failures])
	quit(0 if failures == 0 else 1)
